# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Devin's Awesome Website! 
email: devin@devin.com
description: > # this means to ignore newlines until "baseurl:"
Hello everyone! this is the site that I made today! I deployed using github. As you can see from the url.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: devinb
github_username:  devinb

# Build settings
markdown: kramdown
